// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VP_V2.Data;

#nullable disable

namespace VP_V2.Migrations
{
    [DbContext(typeof(VP_DBcontext))]
    [Migration("20230611225435_VP1002")]
    partial class VP1002
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VP_V2.Models.Cliente", b =>
                {
                    b.Property<int>("IdCli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCli"));

                    b.Property<string>("Ape")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cod_Tel")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Dni")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("Fecha_Baja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LocalidadIdLoc")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tel")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdCli");

                    b.HasIndex("LocalidadIdLoc");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("VP_V2.Models.Localidade", b =>
                {
                    b.Property<int>("IdLoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoc"));

                    b.Property<string>("Cod_Postal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nom_Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProvinciaIdProv")
                        .HasColumnType("int");

                    b.HasKey("IdLoc");

                    b.HasIndex("ProvinciaIdProv");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("VP_V2.Models.Producto", b =>
                {
                    b.Property<int>("IdProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProd"));

                    b.Property<string>("Desc_Prod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha_Baja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio_Costo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Precio_Venta")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("IdProd");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("VP_V2.Models.Provincia", b =>
                {
                    b.Property<int>("IdProv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProv"));

                    b.Property<string>("Nom_Prov")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProv");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("VP_V2.Models.Usuario", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<int?>("ClienteIdCli")
                        .HasColumnType("int");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUser");

                    b.HasIndex("ClienteIdCli");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VP_V2.Models.Cliente", b =>
                {
                    b.HasOne("VP_V2.Models.Localidade", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadIdLoc");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("VP_V2.Models.Localidade", b =>
                {
                    b.HasOne("VP_V2.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaIdProv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("VP_V2.Models.Usuario", b =>
                {
                    b.HasOne("VP_V2.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdCli");

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
